# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-01 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_gm'),
    ]

    operations = [
        migrations.AddField(
            model_name='gm',
            name='link',
            field=models.CharField(max_length=2048, null=True, verbose_name='超链接'),
        ),
        migrations.AddField(
            model_name='jd',
            name='link',
            field=models.CharField(max_length=2048, null=True, verbose_name='超链接'),
        ),
        migrations.AddField(
            model_name='sn',
            name='link',
            field=models.CharField(max_length=2048, null=True, verbose_name='超链接'),
        ),
        migrations.AddField(
            model_name='tm',
            name='link',
            field=models.CharField(max_length=2048, null=True, verbose_name='超链接'),
        ),
    ]
